---
           - name: 1. Update APT package manager repositories cache
             become: true
             apt:
               update_cache: yes

           - name: 2. Install mysql server package
             apt: name=mysql-server state=present

           - name: 3. mysql configuration
             lineinfile:
               path: /etc/mysql/mysql.conf.d/mysqld.cnf
               # The String to Search
               regexp: "bind-address" 
               # The String to Replace
               line: "bind-address            = 0.0.0.0"
               state: present
               backup: yes
           
           - name: 3. Start Mysql Service
             service: name=mysql state=started enabled=true

           - name: 4. Install python Mysql package #required for mysql_db tasks 
             apt: name=python-mysqldb state=present
           
           - name: 5. Create a new database
             mysql_db: name=demo state=present collation=utf8_general_ci
           
           - name: 6. Create a database user
             mysql_user: name=remoteusr password=remotepwd priv=*.*:ALL host=% state=present
           
           - name: 6a. Copy sample data
             copy: src=users.sql dest=/tmp/users.sql
           
           - name: 6b. Insert sample data
             shell: cat /tmp/users.sql | mysql -u remoteusr -premotepwd demo

           - name: 7. ReStart Mysql Service
             service: name=mysql state=restarted
